config/routes.rb
Neon::Application.routes.draw do

  get "inventory/index"
  get "inventory/import"
  resources :timelines, :av_devices, :printers,:idevices, :devices  do
    collection { post :import }
  end
  
  devise_for :users,  :controllers => {:sessions => "sessions"},:path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}  #devise_for :users

  root 'welcome#index'

  
  get "/graph", to: "charts#graph",  as: "graph"
  get "/pie", to: "charts#pie",  as: "pie"
  get "/bar", to: "charts#bar",  as: "bar"
  get "/upload", to: "inventory#index", as: "upload_inventory" 
  post "/inventory/import", to: "inventory#import", as: "import_inventory"

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  
  def self.import(file)
    spreadsheet = Import::Uploader.open_spreadsheet(file)
    
    spreadsheet.sheets.each do |sheet| 
      spreadsheet.default_sheet = sheet
      header = spreadsheet.row(1)
      if !header.blank?
        logger.info "Spreadsheet :: #{spreadsheet.inspect}"
        logger.info "HEADER:: #{header.inspect}"
        
        
        if is_device_sheet(header, sheet)
          Device.submit_sheet(spreadsheet)
        elsif is_idevice_sheet(header, sheet)
          Idevice.submit_sheet(spreadsheet)
        elsif is_printer_sheet(header, sheet)
          Printer.submit_sheet(spreadsheet)
        elsif is_avinteractive_sheet(header, sheet)
          AvInteractive.submit_sheet(spreadsheet)
        elsif is_timeline_sheet(header, sheet)
          ComputerTimeline.submit_sheet(spreadsheet)
        end
      end
    end
  end
  
  def self.is_device_sheet(header, sheet)
    if sheet.downcase == 'master' && (header.include? "Computer Name")
      return true
    end
    return false
  end
  
  def self.is_idevice_sheet(header, sheet)
    if sheet.downcase == 'idevices' #&& (header.include? "Serial Number") && (header.include? "Asset Tag")
      return true
    end
    return false
  end
  
  def self.is_printer_sheet(header, sheet)
    if sheet.downcase == 'printers' #&& (header.include? "Printer")
      return true
    end
    return false
  end
  
  def self.is_avinteractive_sheet(header, sheet)
    if sheet.downcase == 'av - interactive' #&& (header.include? "Serial") && (header.include? "Brand")
      return true
    end
    return false
  end
  
  def self.is_timeline_sheet(header, sheet)
    if sheet.downcase == 'computer timeline' #&& (header.include? "Device") && (header.include? "Date of Service")
      return true
    end
    return false
  end
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  before_action :authenticate_user!
  def index
  end
  
  def import
    Processheet.process_all(params[:file])
   redirect_to root_path, notice: "Inventory imported."
  end
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/views/inventory/import.html.haml
%h1 Inventory#import
%p Find me in app/views/inventory/import.html.haml

app/views/inventory/index.haml
.page-header
  %h1=t '.title', :default => "Inventory".titleize
%table.table.table-striped
  %thead
    %tr
      %td= link_to "Devices", devices_path
      %td= link_to "Idevices", idevices_path
      %td= link_to "Printers", printers_path
      %td= link_to "AV Interactive", av_interactives_path
      %td= link_to "Computer Timeline", computer_timelines_path
 
.sample
  = form_tag import_devices_path, multipart: true do
    = file_field_tag :file
    = submit_tag "Import"
    
  = link_to "Sample XLS", '/docs/Sample.xlsx'

app/views/inventory/index.html.haml
= render '/shared/import', file_name: "Upload_all.xlsx", import_path: import_inventory_path